name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.1.763'
    - name: run clj-prolog unit tests
      run: clojure -M:dev:test
